#preload = ~/nixos-dotfiles/home-manager/programs/hypr/wall/wall2.jpg
#preload = ~/nixos-dotfiles/home-manager/programs/hypr/wall/windows.png
#preload = ~/wallpapers/red.png
preload = ~/wallpapers/nature.jpg
preload = ~/wallpapers/windows.png
preload = ~/wallpapers/nixos.jpg
wallpaper = ,~/wallpapers/nature.jpg
